### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by sunshantong** [j96w/6-PACK#25]
Hi,   thank you for your work! When I run _python benchmark.py_, the following occurred:

```
1
bottle_red_stanford_norm
benchmark.py:102: RuntimeWarning: invalid value encountered in arccos
  theta = np.arccos(y1.dot(y2) / (np.linalg.norm(y1) * np.linalg.norm(y2)))
bottle_shampoo_norm
bottle_shengjun_norm
bowl_shengjun_norm
benchmark.py:116: RuntimeWarning: invalid value encountered in arccos
  theta = np.arccos((np.trace(R) - 1) / 2)
bowl_blue_white_chinese_norm
bowl_white_small_norm
Traceback (most recent call last):
  File "benchmark.py", line 264, in <module>
    main() 
  File "benchmark.py", line 199, in main
    gt_pose = result['gt_RTs'][num_idx]
IndexError: index 4 is out of bounds for axis 0 with size 4
```
Can you give me some suggestions?  Thank you very much.

**Comment by LyuJ1998** [comment]
Hi, please see [Issue 16](https://github.com/j96w/6-PACK/issues/16)

**Comment by LyuJ1998** [comment]
Hi, please see [Issue#16](https://github.com/j96w/6-PACK/issues/16).

**Comment by xsf777** [comment]
so how to solve?
