### ISSUE TITLE
benchmark indexError

### ISSUE THREAD

**Issue by qzhou711** [j96w/6-PACK#27]
Hi, thanks for your great work.
In the evaluation step, I have generated the estimated pose results of each frame by **eval.py**.
When I try to get the final results  using **benchmark.py**, I got the error of IndexError. Could you tell me how to solve it?
```
python benchmark.py 
3
bowl_blue_white_chinese_norm
bowl_shengjun_norm
bowl_white_small_norm
Traceback (most recent call last):
  File "benchmark.py", line 271, in <module>
    main() 
  File "benchmark.py", line 206, in main
    gt_pose = result['gt_RTs'][num_idx]
IndexError: index 4 is out of bounds for axis 0 with size 4
```

**Comment by Xenos24R** [comment]
Hi,bamboosdu
I have the same problem as you,Did you solve it.If you have already solved it, can you tell me the solution?
Look forward to hearing from you.
