### ISSUE TITLE
ModuleNotFoundError: No module named 'libs.knn.knn_pytorch._knn_pytorch'

### ISSUE THREAD

**Issue by xsf777** [j96w/6-PACK#33]
D:\Users\xsf\PycharmProjects\6-PACK-master\libs\transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Traceback (most recent call last):
  File "D:/Users/xsf/PycharmProjects/6-PACK-master/train.py", line 18, in <module>
    from libs.loss import Loss
  File "D:\Users\xsf\PycharmProjects\6-PACK-master\libs\loss.py", line 11, in <module>
    from libs.knn.__init__ import KNearestNeighbor
  File "D:\Users\xsf\PycharmProjects\6-PACK-master\libs\knn\__init__.py", line 7, in <module>
    from libs.knn import knn_pytorch as knn_pytorch
  File "D:\Users\xsf\PycharmProjects\6-PACK-master\libs\knn\knn_pytorch\__init__.py", line 3, in <module>
    from ._knn_pytorch import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'libs.knn.knn_pytorch._knn_pytorch'

Process finished with exit code 1

**Comment by xsf777** [comment]
This is problem in windows.It  disappears in linux.
