### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'My_NOCS/data_list/real_val/1/'

### ISSUE THREAD

**Issue by xsf777** [j96w/6-PACK#34]

**Comment by xsf777** [comment]
Traceback (most recent call last):
  File "/home/xsf/Documents/6-PACK-master/benchmark.py", line 265, in <module>
    main() 
  File "/home/xsf/Documents/6-PACK-master/benchmark.py", line 238, in main
    all_score[-1].append(cls_in_5_5/cls_num)
ZeroDivisionError: division by zero

**Comment by xsf777** [comment]
this problem had been finished.
